CREATE DATABASE eSHOPPING_DB;
GO
-- 1. Nếu CSDL đã tồn tại, ngắt mọi kết nối dở dang và xóa để làm sạch
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'eSHOPPING_DB')
BEGIN
    ALTER DATABASE eSHOPPING_DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE eSHOPPING_DB;
END
GO

-- 2. Tạo Cơ sở dữ liệu mới
CREATE DATABASE eSHOPPING_DB;
GO

USE eSHOPPING_DB;
GO

-- 3. BẢNG NHÓM SẢN PHẨM
CREATE TABLE NHOMSANPHAM (
    MaNhom NVARCHAR(20) PRIMARY KEY,
    TenNhom NVARCHAR(100) NOT NULL
);

-- 4. BẢNG SẢN PHẨM
CREATE TABLE SANPHAM (
    MaSP NVARCHAR(20) PRIMARY KEY,
    TenSP NVARCHAR(200) NOT NULL,
    MaNhom NVARCHAR(20) NOT NULL,
    NhaSanXuat NVARCHAR(100),
    HinhAnh NVARCHAR(255),
    MoTa NVARCHAR(MAX),
    ThongSoKyThuat NVARCHAR(MAX),
    GiaBan DECIMAL(18, 2) NOT NULL CHECK (GiaBan >= 0),
    SoLuongTon INT NOT NULL DEFAULT 0 CHECK (SoLuongTon >= 0),
    TrangThai NVARCHAR(50) DEFAULT N'Còn hàng',
    CONSTRAINT FK_SANPHAM_NHOM FOREIGN KEY (MaNhom) REFERENCES NHOMSANPHAM(MaNhom) ON DELETE CASCADE
);

-- 5. BẢNG KHÁCH HÀNG
CREATE TABLE KHACHHANG (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    CMND_Passport VARCHAR(20) NOT NULL,
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(15),
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    Email VARCHAR(100)
);

-- 6. BẢNG GIỎ HÀNG
CREATE TABLE GIOHANG (
    MaGioHang INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL UNIQUE,
    NgayTao DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_GIOHANG_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH) ON DELETE CASCADE
);

-- 7. BẢNG CHI TIẾT GIỎ HÀNG
CREATE TABLE CHITIETGIOHANG (
    MaGioHang INT NOT NULL,
    MaSP NVARCHAR(20) NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    PRIMARY KEY (MaGioHang, MaSP),
    CONSTRAINT FK_CTGH_GIOHANG FOREIGN KEY (MaGioHang) REFERENCES GIOHANG(MaGioHang) ON DELETE CASCADE,
    CONSTRAINT FK_CTGH_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- 8. BẢNG HÌNH THỨC GIAO HÀNG
CREATE TABLE HINHTHUCGIAOHANG (
    MaHTGH INT IDENTITY(1,1) PRIMARY KEY,
    TenHTGH NVARCHAR(100) NOT NULL,
    PhiCoDinh DECIMAL(18, 2) NOT NULL DEFAULT 0
);

-- 9. BẢNG THÔNG TIN NGƯỜI NHẬN
CREATE TABLE NGUOINHAN (
    MaNguoiNhan INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(15) NOT NULL
);

-- 10. BẢNG THANH TOÁN
CREATE TABLE THANHTOAN (
    MaThanhToan INT IDENTITY(1,1) PRIMARY KEY,
    LoaiThe VARCHAR(20) NOT NULL,
    SoTheMasked VARCHAR(20) NOT NULL,
    PhiGiaoDich DECIMAL(18, 2) DEFAULT 0,
    NgayThanhToan DATETIME DEFAULT GETDATE(),
    TrangThaiThanhToan NVARCHAR(50) DEFAULT N'Thành công'
);

-- 11. BẢNG ĐƠN HÀNG
CREATE TABLE DONHANG (
    MaDonHang INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    MaNguoiNhan INT NOT NULL,
    MaHTGH INT NOT NULL,
    MaThanhToan INT NOT NULL,
    NgayDat DATETIME DEFAULT GETDATE(),
    TongTienHang DECIMAL(18, 2) NOT NULL CHECK (TongTienHang >= 0),
    PhiGiaoHang DECIMAL(18, 2) NOT NULL DEFAULT 0 CHECK (PhiGiaoHang >= 0),
    TongThanhToan DECIMAL(18, 2) NOT NULL CHECK (TongThanhToan >= 0),
    TrangThai NVARCHAR(50) DEFAULT N'DatHang',
    CONSTRAINT FK_DONHANG_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_DONHANG_NGUOINHAN FOREIGN KEY (MaNguoiNhan) REFERENCES NGUOINHAN(MaNguoiNhan),
    CONSTRAINT FK_DONHANG_HTGH FOREIGN KEY (MaHTGH) REFERENCES HINHTHUCGIAOHANG(MaHTGH),
    CONSTRAINT FK_DONHANG_THANHTOAN FOREIGN KEY (MaThanhToan) REFERENCES THANHTOAN(MaThanhToan)
);

-- 12. BẢNG CHI TIẾT ĐƠN HÀNG
CREATE TABLE CHITIETDONHANG (
    MaDonHang INT NOT NULL,
    MaSP NVARCHAR(20) NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(18, 2) NOT NULL CHECK (DonGia >= 0),
    ThanhTien AS (SoLuong * DonGia),
    PRIMARY KEY (MaDonHang, MaSP),
    CONSTRAINT FK_CTDH_DONHANG FOREIGN KEY (MaDonHang) REFERENCES DONHANG(MaDonHang) ON DELETE CASCADE,
    CONSTRAINT FK_CTDH_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);
GO

-- 13. CHÈN DỮ LIỆU MẪU
INSERT INTO NHOMSANPHAM (MaNhom, TenNhom) VALUES 
(N'NSP01', N'Điện thoại & Máy tính bảng'),
(N'NSP02', N'Laptop & Máy tính xách tay'),
(N'NSP03', N'Phụ kiện điện tử');

INSERT INTO SANPHAM (MaSP, TenSP, MaNhom, NhaSanXuat, GiaBan, SoLuongTon, TrangThai) VALUES
(N'SP001', N'iPhone 15 Pro Max 256GB', N'NSP01', N'Apple', 29990000, 10, N'Còn hàng'),
(N'SP002', N'Samsung Galaxy S24 Ultra', N'NSP01', N'Samsung', 26990000, 5, N'Còn hàng'),
(N'SP003', N'MacBook Air M2 13 inch', N'NSP02', N'Apple', 24990000, 0, N'Hết hàng');

INSERT INTO HINHTHUCGIAOHANG (TenHTGH, PhiCoDinh) VALUES
(N'Giao hàng thường', 30000),
(N'Giao hàng nhanh', 50000),
(N'Giao hàng nhanh trong ngày', 100000);
GO